# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

MEMBER_ACCOUNT_ROLE_NAME = 'BillingConsolePolicyMigratorRole'
MAX_WORKERS_FOR_UPDATE_SCRIPT = 30
MAX_WORKERS_FOR_IDENTIFY_SCRIPT = 20
MAX_PAGE_ITEMS = 10
ACCOUNT_ID_LENGTH = 12
PERMISSION_SET_STATUS_CHECKER_SLEEP_TIME = 15  # Time in seconds
PERMISSION_SET_STATUS_CHECKER_RETRIES = 80  # Retry count
